### ISSUE TITLE
Add open-source license

### ISSUE THREAD

**Issue by cstigler** [nuorder/zencoder-promises#1]
Hi! We love your module (and want to use it) at [Zaption](http://www.zaption.com), but it currently doesn't have a license which means it's by default copyrighted under US law. Could you please add an open-source license so we can use it in our project?

We recommend the [MIT License](https://tldrlegal.com/license/mit-license), but you can learn more about licensing at [TLDRLegal](https://tldrlegal.com). Thanks!

**Comment by jessedpate** [comment]
Hi, I added a license for you.

Glad to help out!

**Comment by cstigler** [comment]
Thank you!
